### ISSUE TITLE
When used with react-navigation undefineds createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by afeichuanqi** [reactrondev/react-native-web-swiper#11]
When used with react-navigation undefineds createMaterialTopTabNavigator. there is a strange phenomenon when sliding, which first responds to TopTabNavigator, and causes the sliding page to be stuck in half.

**Comment by afeichuanqi** [comment]
It has been settled. Break the plug-in's gesture permissions from the beginning.

Use:

OnStart ShouldSetPanResponder: (evt, gesture State) => true,

OnStart ShouldSetPanResponder Capture: (evt, gesture State) => true,

OnMoveShouldSetPanResponder: (evt, gesture State) => true,

OnMoveShouldSetPanResponder Capture: (evt, gesture State) => true,

Prevent react-navigation from getting secondary privileges leading to abnormal sliding

**Comment by oxyii** [comment]
Thanks for your report! Can you create a [snack](https://snack.expo.io) with this bug?

**Comment by afeichuanqi** [comment]
> Thanks for your report! Can you create a [snack](https://snack.expo.io) with this bug? @afeichuanqi

Just tried it and it didn't work out.

OnStart ShouldSetPanResponder: (evt, gesture State) => true,

OnStart ShouldSetPanResponder Capture: (evt, gesture State) => true,

OnMoveShouldSetPanResponder: (evt, gesture State) => true,

OnMoveShouldSetPanResponder Capture: (evt, gesture State) => true,

Interception of privileges will cause onPress to fail to click. I don't know how to show it to you because I haven't used Expo. I hope there is a solution. The top bar of react-navigation will slide ahead of your plug-in.

**Comment by afeichuanqi** [comment]
I've tried several swiper plug-ins that don't solve my problem. There are small bugs. Maybe I used swiper in Scrollview of react-native topbar to cause various swiper plug-in bugs

**Comment by oxyii** [comment]
@afeichuanqi I can try to reproduce it after weekend only. But you can try to make a snack. Expo includes native modules of `react-navigation`. If problem exactly with swiper copabality with react-navigation then it must replay on snack

**Comment by afeichuanqi** [comment]
Perhaps it's because react-native-gesture-handler, which react-navigation defaults to, makes react-native's own touch impossible to truncate its privileges.

**Comment by oxyii** [comment]
@afeichuanqi I added some minimal distance before swiper will handle gesture (#4).
https://github.com/oxyii/react-native-web-swiper/blob/3517a7f69be3bce835e75876004b520efbbefb77/src/index.js#L86
May be this is a problem? Can you share minimal part of your case for reproducing?

**Comment by afeichuanqi** [comment]
> @afeichuanqi I added some minimal distance before swiper will handle gesture (#4).
> https://github.com/oxyii/react-native-web-swiper/blob/3517a7f69be3bce835e75876004b520efbbefb77/src/index.js#L86
> 
> 
> May be this is a problem? Can you share minimal part of your case for reproducing?

The most important part of the problem is that react-navigation is greater than your native touch gesture permission, causing the gesture to respond to navigation when the child component slides.
So I can't solve the problem of not breaking the navigation gesture.

**Comment by afeichuanqi** [comment]
@oxyii 有新版本出来吗

**Comment by oxyii** [comment]
@afeichuanqi I can't speak chinesse. Thank to Google Translator:

> Is there a new version?

Nope. I'm waiting a [snack](https://snack.expo.io) with reproducing from you

**Comment by afeichuanqi** [comment]
@oxyii I try to

OnMoveShouldSetPanResponderCapture: (a, c) = > {

If (! This. Props. SwipingEnabled) return! 1;

This. Props. OnAnimationStart && enclosing props. The onAnimationStart ();

Const d = 5 < b("row" == this. Props. Direction? C.d x: c.d y);

Return true;

},



Let him always return true; It works on android, but my item doesn't have an onClick event anymore. I'd love to give you a demo but the project is complicated and messy. So it's hard to give you a demo

**Comment by oxyii** [comment]
@afeichuanqi 

> Let him always return true

```jsx
<Swiper minDistanceToCapture={0}>
...
</Swiper>
```

So, https://github.com/oxyii/react-native-web-swiper/blob/d3d19de0ac243f857b9dc644a09b3cac8ce52283/src/Swiper.js#L110-L112 will return `true` on any gesture action

**Comment by afeichuanqi** [comment]
@oxyii How about I make a demo and upload it to github?

**Comment by oxyii** [comment]
@afeichuanqi Sure!

**Comment by afeichuanqi** [comment]
@oxyii  我已经发布在github https ://github.com/afeichuanqi/demo_swiper/tree/master ,There is an mp4 in the /data directory for you to see

**Comment by afeichuanqi** [comment]
@oxyii https ://github.com/afeichuanqi/demo_swiper

**Comment by afeichuanqi** [comment]
@oxyii Thank you very much for helping me. I have temporarily chosen another one that is more suitable for my business in some ways. It's bothering you, too.

**Comment by oxyii** [comment]
@afeichuanqi Thank you. I will digging [it](https://github.com/oxyii/swiper-bug-11)

**Comment by jarvisluong** [comment]
It seems that the issue is stale so I will close this one
