### ISSUE TITLE
Rerender swiper

### ISSUE THREAD

**Issue by YevheniiShabelnykkk** [reactrondev/react-native-web-swiper#22]
Hello!
Now, if state was changed, swiper won't be changed.
Can you add this functionality, because it's really needed.
Thanks!

**Comment by sakhmedbayev** [comment]
What??? This is not good behavior. Why in the world `Swiper` does not rerender???

**Comment by Jorge-Luis-Rangel-Peralta** [comment]
Why not simply use a key change as a workaround?, i agree is is unacceptable that it does not change when the props change, but in the mind-time the key change works: 

`const Component = ({ children }) => {
    const keyValue = useMemo(() => someKeyGenerator(), [children])

    return (
        <Swiper key={keyValue}>{children}</Swiper>
    )
}`

**Comment by Shing-Ho** [comment]
Thanks @Jorge-Luis-Rangel-Peralta this is working as great.
I add uuidv4 into key and it's working well.

**Comment by dhirajanand014** [comment]
This is really needed for us

**Comment by kopax** [comment]
@Jorge-Luis-Rangel-Peralta what about if I want to get the `isSwiping` state using `onAnimationStart` and `onAnimationEnd`, and update the content of the view ? I keep having no rerender of the cards as I am not editing `children` which is passed upper in the JSX tree. Did anyone found a workaround for this?

**Comment by jorgezerpa** [comment]
> Why not simply use a key change as a workaround?, i agree it is unacceptable that it does not change when the props change, but in the mind-time the key change works:
> 
> ```
> const Component = ({ children }) => {
>     const keyValue = useMemo(() => someKeyGenerator(), [children])
> 
>     return (
>         <Swiper key={keyValue}>{children}</Swiper>
>     )
> }
> ```
> 
> It's not pretty but works



> Why not simply use a key change as a workaround?, i agree it is unacceptable that it does not change when the props change, but in the mind-time the key change works:
> 
> ```
> const Component = ({ children }) => {
>     const keyValue = useMemo(() => someKeyGenerator(), [children])
> 
>     return (
>         <Swiper key={keyValue}>{children}</Swiper>
>     )
> }
> ```
> 
> It's not pretty but works

This works perfectly for me!! thanks a lot @Jorge-Luis-Rangel-Peralta
