### ISSUE TITLE
Reset Swiper From props

### ISSUE THREAD

**Issue by chayancbnits** [reactrondev/react-native-web-swiper#25]
I have 4 swiper items and from={1}. So I am swiping one by one so therefore current swiper index is 2,  how to reset "from" props when componentWillUnmount function call?

**Comment by oxyii** [comment]
@chayancbnits swiper must reset it-self on next mount... But if you want to animated slide to initial index (1) before unmount event you can do it by ref. Something like this:
```jsx
class SwiperWrapper extends React.Component {
  swiperRef;

  componentWillUnmount() {
    this.swiperRef && this.swiperRef.goTo(1);
  }

  render() {
    return (
      <Swiper ref={swiperInstance => this.swiperRef = swiperInstance} from={1}>
        ...
      </Swiper>
    );
  }
}
```

See [last chapter of README](https://github.com/oxyii/react-native-web-swiper#interaction-methods) for details

**Comment by chayancbnits** [comment]
In my case. All the components are in the same Stack Navigator. So the React Life Cycle Methods does not work for me in Swiper Wrapper Component.
I have make a Workaround by using the React Navigation Event "isFocused" , Something like this:
`
import { withNavigationFocus } from 'react-navigation';
const FeedList = (props) => {
	const swiperRef = useRef(null);
	useEffect(() => {
		if (props.isFocused == false && swiperRef != null) {
			swiperRef.current.goTo(0)
		}
	})
	return (
		<Swiper
			ref={swiperRef}
			controlsEnabled={false}
			from={0}>
			.....
			</Swiper>
	)
}
export default compose(connect(null, null), withNavigationFocus)(React.memo(FeedList));

`
Is this a better approach?

**Comment by jarvisluong** [comment]
Hi! This issue has been inactive for a long time, hence closed.
