### ISSUE TITLE
When I am swiping left and right , sometime it is lagging, some part of next or previous page is getting stuck in present page.  

### ISSUE THREAD

**Issue by SupriyaGo** [reactrondev/react-native-web-swiper#33]

**Comment by SupriyaGo** [comment]
please refer to the link for the video of this issue.
[https://drive.google.com/open?id=1kEnLPG-tdOTL1uSWQUQPcEyA03ElYzfO](url)

**Comment by jarvisluong** [comment]
Hi! I'm closing this issue since there is no update in the last 90 days! Feel free to create a new issue if needed.
