### ISSUE TITLE
gesturesEnabled is boolean in index.d.ts

### ISSUE THREAD

**Issue by 28harishkumar** [reactrondev/react-native-web-swiper#34]
For typescipt, `gesturesEnabled` is `boolean` in index.d.ts but it is `PropTypes.func` in `src/Swiper.js`

It raises error in [line 103](https://github.com/oxyii/react-native-web-swiper/blob/c7c82bd2760d5dbe035ef2e0410c869646aec6ba/src/Swiper.js#L103)

**Comment by kopax** [comment]
a PR for this would be welcome.

**Comment by jarvisluong** [comment]
Fixed in https://github.com/reactrondev/react-native-web-swiper/commit/1c2d448b2b4d882d57bb2a08efdf8522cb917376
