### ISSUE TITLE
Swipe is not working on a Modal

### ISSUE THREAD

**Issue by ruben-kasaz** [reactrondev/react-native-web-swiper#35]
Hello ! I am using react-native-web-swiper on my project.

When I use it outside a Modal, I can swipe my elements.
But when I try to put the Swiper on Modal, swiping elements is not working.

Do you know how I can do it ?
Thanks

**Comment by Multi-Thinker** [comment]
+1 Same. Also not working in ScrollView

**Comment by Mhmetengineer** [comment]
Hi, I have some problem. Can u solve it?  @ruben-kasaz

**Comment by Kozinecs** [comment]
> +1 Same. Also not working in ScrollView

Did someone manage to use it inside ScrollView?

**Comment by DenisKhatsuk** [comment]
You can try adding onStartShouldSetResponder={() => true} prop to every View child of the Swiper.

[React Native gesture responder system docs](https://reactnative.dev/docs/gesture-responder-system).

I hope this helps.

**Comment by jarvisluong** [comment]
Looks like the solution was provided and the issue was old. Feel free to create a new issue if the same problem persists.
