### ISSUE TITLE
Swiper rerender issue

### ISSUE THREAD

**Issue by somilmathur** [reactrondev/react-native-web-swiper#37]
This is an amazing swiper for sure but the inability to rerender components is kind of a deal-breaker. I would very much like to not have to make separate components just for a simple rerender.

Could you please inform me when you add that functionality? 

I would love to switch back to using your swiper!!

**Comment by Shing-Ho** [comment]
any update?

**Comment by kopax** [comment]
@somilmathur I wonder what you are using which is cross platform, do you have an alternative?

**Comment by Shing-Ho** [comment]
https://github.com/oxyii/react-native-web-swiper/issues/22#issuecomment-567559656
This helps

**Comment by dhirajanand014** [comment]
This is not working along with Array items as well.

**Comment by jarvisluong** [comment]
Fixed in #57
