### ISSUE TITLE
Jest : SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by never00miss** [reactrondev/react-native-web-swiper#38]
There is some problem when i use this with test that jest provide.

this is my jest config, package.json 
`"jest": {
    "roots": [
      "<rootDir>/src"
    ],
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!src/**/*.d.ts"
    ],
    "setupFiles": [
      "react-app-polyfill/jsdom"
    ],
    "setupFilesAfterEnv": [],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
      "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
    ],
    "testEnvironment": "jest-environment-jsdom-fourteen",
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$",
      "^.+\\.module\\.(css|sass|scss)$"
    ],
    "modulePaths": [],
    "moduleNameMapper": {
      "^react-native-web-swiper$": "react-native-web-swiper",
      "^react-native$": "react-native-web",
      "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "web.ts",
      "ts",
      "web.tsx",
      "tsx",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "ttf"
    ],
    "watchPlugins": [
      "jest-watch-typeahead/filename",
      "jest-watch-typeahead/testname"
    ]
  },`

Error Screenshot : 
<img width="1332" alt="Screen Shot 2020-02-18 at 13 13 37" src="https://user-images.githubusercontent.com/10415043/74708942-8296be80-5250-11ea-836e-175133882c43.png">

What i was doin : 
- add "react-native-web-swiper" on "transformIgnorePatterns" on jest config

Appreciate that this library will run on multiple test platform, thx

**Comment by jarvisluong** [comment]
This can be achieved by providing a commonjs build of the package

**Comment by kopax** [comment]
@never00miss you missconfigured with babel within your test:

    Unexpected token export

This error indicate that `es` format is used in your file while babel is not supposed to transpile it, fix your babel configuration for this file and you should be good.

This is not a `react-native-web-swiper` issue and can also be closed.

**Comment by never00miss** [comment]
> @never00miss you missconfigured with babel within your test:
> 
> ```
> Unexpected token export
> ```
> 
> This error indicate that `es` format is used in your file while babel is not supposed to transpile it, fix your babel configuration for this file and you should be good.
> 
> This is not a `react-native-web-swiper` issue and can also be closed.

thx for your answer, working fine for me, and what i am add to do for fixing testing is :
./babelrc
`module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    'module:react-native-dotenv',
  ],
};


./babel.config.js
`module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    'module:react-native-dotenv',
  ],
};
`
