### ISSUE TITLE
LOOKING FOR NEW REPO OWNER

### ISSUE THREAD

**Issue by oxyii** [reactrondev/react-native-web-swiper#42]
I have no time to work on this repo for community. Please comment if you can do it. I will transfer this repo and npm package into your account

**Comment by kopax** [comment]
Hello @oxyii and thanks for sharing this work.

This is a must in the react-native-web ecosystem and I was very pleased to find your work here.

I feel like this is a bad thing for the package that the main maintainer is leaving the project now. May I ask why do you want to leave this project? If it's finance haven't you considered asking for some sponsoring instead? I am pretty sure some corp will be glad to contribute that way so efforts can be shared.

**Comment by oxyii** [comment]
@kopax Thanks for your appreciating this work.
This package was originally written as part of a commercial project. The project owner allowed me to share this package.I did not plan to upgrade the package initially. Just support.

But the features of the package do not satisfy all the needs of the community. Someone needs buttons on top, someone needs a different swipe speed, and so on ... For me personally, the package has enough features. I continue to use version [1.x](https://github.com/oxyii/react-native-web-swiper/tree/3517a7f69be3bce835e75876004b520efbbefb77) in a commercial project.

Now the commercial project has received additional funding. If before he occupied all my working time, now I do not have enough 24 hours in a day. I stopped responding to Issues (( And this is VERY bad for the community. Therefore, I want to give the package in good hands.

**Comment by thanhtunguet** [comment]
I have reviewed the code and want to rewrite it using Typescript ;)

**Comment by oxyii** [comment]
@thanhtunguet Please give me your npm login name, I'll try to transfer package

**Comment by oxyii** [comment]
@thanhtunguet Okay, now you can work with npm package. Thank you for your help!

**Comment by kopax** [comment]
> I have reviewed the code and want to rewrite it using Typescript ;)

Khi nao anh bac dau lam? :)

**Comment by thanhtunguet** [comment]
> > I have reviewed the code and want to rewrite it using Typescript ;)
> 
> Khi nao anh bac dau lam? :)

I have to start working this weekend. I need to modify this package to meet my project requirements and want to upgrade this package using new React features and Typescript

**Comment by oxyii** [comment]
@thanhtunguet Please open issues in your fork. I'll try to transfer existing issues and close issues behavior here.

**Comment by oxyii** [comment]
@thanhtunguet Or delete your fork then I can transfer repo to you

**Comment by kopax** [comment]
Just wondering @thanhtunguet but will you just add Ts or do you have any plan for the future ?

I still see some weird hack to refresh the slider, this for example could be solved internally, I have seen my self doing a lot of hacks in some views to get behond this. Would be nice to know how do you see the futur of this package.

**Comment by thanhtunguet** [comment]
> Just wondering @thanhtunguet but will you just add Ts or do you have any plan for the future?
> 
> I still see some weird hack to refresh the slider, this, for example, could be solved internally, I have seen my self doing a lot of hacks in some views to get beyond this. It would be nice to know how do you see the future of this package.

I just want to rewrite with new React hook api and customize it to meet my requirements. I may not have time in the future to maintain this package and just want to be a contributor, not a maintainer.

**Comment by thanhtunguet** [comment]
> @thanhtunguet Or delete your fork then I can transfer repo to you

Sorry I just want to contribute, not to maintain this package cause I may not have time

**Comment by oxyii** [comment]
@thanhtunguet Okay, I understand. Thank you

**Comment by oxyii** [comment]
@thanhtunguet Please refresh your fork. RNW 0.12 support has been added

**Comment by jarvisluong** [comment]
@oxyii hi! Our company @reactrondev is using this package in our own product and is interested in maintaining this package. Would it be possible to transfer?

**Comment by oxyii** [comment]
@jarvisluong Great! Please provide your npmjs.com account name for invite

**Comment by jarvisluong** [comment]
@oxyii the npmjs account name is reactron.dev 😄

**Comment by oxyii** [comment]
@jarvisluong please add access rights for me on your org here. Exactly - creating new public repos. I cannot transfer without rights

**Comment by jarvisluong** [comment]
@oxyii You should receive an invitation email now

**Comment by oxyii** [comment]
I need access rights here (on github) not on npmjs.com. On npmjs.com you already can publish new builds

**Comment by oxyii** [comment]
Done! Now react-native-web-swiper in @reactrondev org. Thank you!
