### ISSUE TITLE
Swiper dynamic height based on swiper items content

### ISSUE THREAD

**Issue by velidan** [reactrondev/react-native-web-swiper#45]
Is there exists a way to make the swiper dynamic height depend on the Swipe Item content?
eg. 1 swipe item content height: 200px,   2 swipe item content height 100px;
How to make swiper dynamically resizable for the swipe items height? 

Thanks for any help!

**Comment by bikashsahucbnits** [comment]
@velidan this might be helpful
https://github.com/oxyii/react-native-web-swiper/issues/17

**Comment by jarvisluong** [comment]
Hi! I'm closing this issue since there is no update in the last 90 days! Feel free to create a new issue if needed.
