### ISSUE TITLE
Swiper is Laggy on Mobile phones

### ISSUE THREAD

**Issue by vrinch** [reactrondev/react-native-web-swiper#66]
The swiper works very well on desktop browsers, but gets laggy on some mobile phones, while on some, it does not show up at all

**Comment by kopax-polyconseil** [comment]
@vrinch we don't need more information obviously we will help you. Just kidding, what phones ? What code ? Do you have a snack we can use to reproduce?

**Comment by hohoaisan** [comment]
You can use props passed into each slide to determine the logic inside it should be run or not [here](https://github.com/reactrondev/react-native-web-swiper#dynamic-content)
```
type PageProps = {
  index?: number;
  activeIndex?: number;
} & ChapterPage;

export const Page: React.FC<PageProps> = ({index, activeIndex, ...page}) => {
  if (
    index &&
    activeIndex &&
    index !== activeIndex &&
    Math.abs(index - activeIndex) > 2
  ) {
    return null;
  }
  return (
  // rest of the heavy logic of the slide
  )
}
```

**Comment by jarvisluong** [comment]
The issue seems to be stale. Please re-open if this is still needed, thanks.
