### ISSUE TITLE
in iOS ScrollView inside swiper conflict scroll!

### ISSUE THREAD

**Issue by jakil93** [reactrondev/react-native-web-swiper#68]
in ios scrollview and swiper scroll sametime...
but android is okay.

how to fix that?!

![Image of Yaktocat](https://postfiles.pstatic.net/MjAyMTAzMzFfMjIz/MDAxNjE3MTU5MTU4MzUw.kMmaGNCDI6U94oQHkDhqcLZH1QceOyIj_xLC8OsEvrog.jWnZxDjt_V5xrYlUVMzuJWqhH_3FOQmnIUl_U2t2pQUg.GIF.jakil93/ezgif.com-gif-maker.gif?type=w773)

**Comment by oxyii** [comment]
@jakil93 [bounces](https://reactnative.dev/docs/scrollview#bounces-ios)? Also you can try to set `positionFixed ` Swiper prop

**Comment by jakil93** [comment]
@oxyii still sametime scrolling moving.. 😓

**Comment by oxyii** [comment]
@jakil93 I really don't understand what exactly wrong. Did you wanna to hold swiper while ScrollView is moving?

**Comment by jakil93** [comment]
@oxyii 
yes! also, while scrollview moving swiper's gesture must disabled!

while swiper's gesture scrollview's scroll must disabled!

i want exactly that!

**Comment by oxyii** [comment]
@jakil93 You can control it by your-self. Something like this (not tested):

```jsx
import { useState } from 'react';

export default () => {
  const [swiperGestureEnabled, setSwiperGestureEnabled] = useState(true);

  return (
    <ScrollView
      onMomentumScrollBegin={() => setSwiperGestureEnabled(false)}
      onMomentumScrollEnd={() => setSwiperGestureEnabled(true)}
    >
      <Swiper gesturesEnabled={swiperGestureEnabled}>
        <View />
        <View />
      </Swiper>
    </ScrollView>
  );
}
```

**Comment by jakil93** [comment]
@oxyii 
Thanks bro!
but still while swiper gesture working, also scroll view's scroll wokring..

i try to stop scrollview's scroll using by swiper's onAnimationStart/End.
but so slowly...

Do you have another way?

**Comment by jarvisluong** [comment]
the issue seems to be stale. please re-open if this is still needed. thanks
