### ISSUE TITLE
Safari Mobile iOS 12, width and height are always equal to 0

### ISSUE THREAD

**Issue by kopax-polyconseil** [reactrondev/react-native-web-swiper#73]
Hello and thanks for sharing,

We are encountering an issue on the Web with iPhone 6 iOS12 and Safari mobile. The width, height, x and y in Swiper.js are always equal to 0, because onLayout is never called.

Related issues:

- https://github.com/necolas/react-native-web/issues/2161
- https://github.com/pass-culture/pass-culture-app-native/pull/1894

**Comment by jarvisluong** [comment]
Hi! it looks like the original react-native-web project's author has replied to the solution here

https://github.com/necolas/react-native-web/issues/2161#issuecomment-962072910

Hence I will close the issue.
