### ISSUE TITLE
Swiper Doesnt Render Anything

### ISSUE THREAD

**Issue by mpaccione** [reactrondev/react-native-web-swiper#82]
As far as I can tell this doesn't work in any fashion in this Expo app. 
I created a minimum test which does not render any values to the screen.

Version is 
```javascript
    "react-native-web-swiper": "^2.2.3",
```

My import is as follows
```javascript
import Swiper from "react-native-web-swiper";
```

```javascript
 <View>
        {true && (
          <>
            <Text>TEST</Text>
            <Swiper>
              <View>
                <Text>1</Text>
              </View>
              <View>
                <Text>2</Text>
              </View>
            </Swiper>
          </>
        )}
      </View>
```

The TEST text outputs.

My initial goal was something like this 
```javascript
<SwiperContainer>
        {photos && (
          <Swiper>
            {selectedProjectMedia.photos.map((p, idx) => (
              <MediaSlide key={idx} img={p} />
            ))}
          </Swiper>
        )}
      </SwiperContainer>
```
However since I can't get a basic anything working I am probably going to have to find another slider component. 

Any ideas on the issue here?

**Comment by oxyii** [comment]
@mpaccione please add `flex` style to root `View`
https://snack.expo.dev/@oxyii/issues-82

**Comment by mpaccione** [comment]
> @mpaccione please add `flex` style to root `View` https://snack.expo.dev/@oxyii/issues-82

Gotcha, I saw that in the example. This was my mistake in assuming that it would still render to the screen albeit in a non functioning layout. It would seem that the underlying code relies on that otherwise you wont see any output. 

Thank you kindly.

**Comment by mpaccione** [comment]
Okay, so I had anticipated this would solve it but it seems like the slider doesn't rerender?

In the below image I am consoling out the photo values which are mock base64...
```javascript
  console.log({ photos });
  console.log(selectedProjectMedia.photos)
```
![image](https://user-images.githubusercontent.com/8552642/170380692-43933403-9d45-4023-9fd4-abf69d21ccdf.png)

```javascript
{photos && (
        <View style={{ flex: 1 }}>
          <Swiper>
            {selectedProjectMedia.photos.map((p, idx) => (
              <View style={{ backgroundImage: `url(${p})` }} key={idx}>
                <Text>{idx}</Text>
              </View>
            ))}
          </Swiper>
        </View>
      )}
```

Is there a manual rerender on this? I am assuming it is not rerendering as the console is outputting the react component rerendered values from redux.

**Comment by mpaccione** [comment]
Okay I am definitely closing this out. The main difference in my experience using this package is there cannot be ANY style issues. In many other packages you're going to get some output regardless. However, my experience is mostly web react and not native. I suppose I take error handling for granted in web packages. Will have to kick that habit for native.

Quick fix in prepending with the data bit for base64.
```<View style={{ backgroundImage: `url(data:image/png;base64,${p})` }} key={idx}>```
